config/routes.rb
Rails.application.routes.draw do
  devise_for :ore_users
  resources :oremeshis
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'oremeshis#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, presence: true
end

app/models/ore_user.rb
class OreUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :lockable, :timeoutable, :trackable

  mount_uploader :OreImage, ImageUploader
end

app/models/oremeshi.rb
class Oremeshi < ApplicationRecord
    mount_uploader :finalimage, ImageUploader
end

class Oremeshi < ApplicationRecord
    mount_uploader :image1, ImageUploader
end

class Oremeshi < ApplicationRecord
    mount_uploader :image2, ImageUploader
end

class Oremeshi < ApplicationRecord
    mount_uploader :image3, ImageUploader
end

class Oremeshi < ApplicationRecord
    mount_uploader :image4, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  # 省略

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username], keys: [:OreImage])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username], keys: [:OreImage])
    
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end

end

app/controllers/oremeshis_controller.rb
class OremeshisController < ApplicationController
  before_action :set_oremeshi, only: [:show, :edit, :update, :destroy]

  # GET /oremeshis
  # GET /oremeshis.json
  def index
    @oremeshis = Oremeshi.all
  end

  # GET /oremeshis/1
  # GET /oremeshis/1.json
  def show
  end

  # GET /oremeshis/new
  def new
    @oremeshi = Oremeshi.new
  end

  # GET /oremeshis/1/edit
  def edit
  end

  # POST /oremeshis
  # POST /oremeshis.json
  def create
    @oremeshi = Oremeshi.new(oremeshi_params)

    respond_to do |format|
      if @oremeshi.save
        format.html { redirect_to @oremeshi, notice: 'Oremeshi was successfully created.' }
        format.json { render :show, status: :created, location: @oremeshi }
      else
        format.html { render :new }
        format.json { render json: @oremeshi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oremeshis/1
  # PATCH/PUT /oremeshis/1.json
  def update
    respond_to do |format|
      if @oremeshi.update(oremeshi_params)
        format.html { redirect_to @oremeshi, notice: 'Oremeshi was successfully updated.' }
        format.json { render :show, status: :ok, location: @oremeshi }
      else
        format.html { render :edit }
        format.json { render json: @oremeshi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oremeshis/1
  # DELETE /oremeshis/1.json
  def destroy
    @oremeshi.destroy
    respond_to do |format|
      format.html { redirect_to oremeshis_url, notice: 'Oremeshi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oremeshi
      @oremeshi = Oremeshi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def oremeshi_params
      params.require(:oremeshi).permit(:title, :ingre, :step1, :step2, :step3, :step4, :final, :time, :category, :finalimage, :image1, :image2, :image3, :image4)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/oremeshis_helper.rb
module OremeshisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>魁!!漢飯</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %></p>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %></p>
  </head>

  <body>
    <div class="container">
      <nav>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="user_menu">
      <% if ore_user_signed_in? %>
        <%= link_to image_tag(current_ore_user.OreImage.url, :size =>'70x70'), root_path %>
        <p><%= link_to '編集', edit_ore_user_registration_path %></p>
        <p><%= link_to '破門', destroy_ore_user_session_path, method: :delete %></p>
      <% else %>
        <p><%= link_to '入門', new_ore_user_registration_path %></p>
        <p><%= link_to '見参', new_ore_user_session_path %></p>
        <% end %>
      </div>
      </nav>
      <h1><%= link_to image_tag('/assets/header.png', class: 'logo'), root_path %></h1>
    <%= yield %>
    </div>
  </body>
</html>

app/views/oremeshis/_form.html.erb
<%= form_with(model: oremeshi, local: true) do |form| %>
  <% if oremeshi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(oremeshi.errors.count, "error") %> prohibited this oremeshi from being saved:</h2>

      <ul>
      <% oremeshi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= "名" %>
    <!--<%= form.label :title %>-->
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= "具" %>
    <!--<%= form.label :ingre %>-->
    <%= form.text_area :ingre %>
  </div>

  <div class="field">
    <%= "流 一" %>
    <!--<%= form.label :step1 %>-->
    <%= form.text_field :step1 %>
  </div>

  <div class="field">
    <!--<%= form.label :final %>-->
    <%= form.file_field :image1 %>
  </div>

  <div class="field">
    <%= "流 二" %>
    <!--<%= form.label :step2 %>-->
    <%= form.text_field :step2 %>
  </div>

  <div class="field">
    <!--<%= form.label :final %>-->
    <%= form.file_field :image2 %>
  </div>

  <div class="field">
    <%= "流 三" %>
    <!--<%= form.label :step3 %>-->
    <%= form.text_field :step3 %>
  </div>

  <div class="field">
    <!--<%= form.label :final %>-->
    <%= form.file_field :image3 %>
  </div>

  <div class="field">
    <%= "流 四" %>
    <!--<%= form.label :step4 %>-->
    <%= form.text_field :step4 %>
  </div>

  <div class="field">
    <!--<%= form.label :final %>-->
    <%= form.file_field :image4 %>
  </div>

  <div class="field">
    <%= "流 五" %>
    <!--<%= form.label :final %>-->
    <%= form.text_field :final %>
  </div>

  <div class="field">
    <!--<%= form.label :final %>-->
    <%= form.file_field :finalimage %>
  </div>

  <div class="field">
    <%= "時" %>
    <!--<%= form.label :time %>-->
    <%= form.number_field :time %>
  </div>

  <div class="field">
    <%= "属" %>
    <!--<%= form.label :category %>-->
    <%= form.text_area :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/oremeshis/edit.html.erb
<h1>Editing Oremeshi</h1>

<%= render 'form', oremeshi: @oremeshi %>

<%= link_to 'Show', @oremeshi %> |
<%= link_to 'Back', oremeshis_path %>

app/views/oremeshis/index.html.erb
<p id="notice"><%= notice %></p>

<div class="content">
<div class="head">
  <h1>俺飯</h1>
  <h3><%= link_to '新兵追加', new_oremeshi_path %></h3>
</div>

<table>
  <thead>
    <tr>
      <!--
      <th>Title</th>
      <th>Ingre</th>
      <th>Step1</th>
      <th>Step2</th>
      <th>Step3</th>
      <th>Step4</th>
      <th>Final</th>
      <th>Time</th>
      <th>Category</th>
      -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @oremeshis.each do |oremeshi| %>
      <tr>
        <div class="meshi_title">
          <td><h4>❏ <%= oremeshi.title %><h4></td>
        </div>
        <!--
        <td><%= oremeshi.ingre %></td>
        <td><%= oremeshi.step1 %></td>
        <td><%= oremeshi.step2 %></td>
        <td><%= oremeshi.step3 %></td>
        <td><%= oremeshi.step4 %></td>
        <td><%= oremeshi.final %></td>
        <td><%= oremeshi.time %></td>
        <td><%= oremeshi.category %></td>
        <td><%= link_to 'Show', oremeshi %></td>
        <td><%= link_to '編集', edit_oremeshi_path(oremeshi) %></td>
        <td><%= link_to '削除', oremeshi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->        
      </tr>
      <tr>   
        <div class="meshi_thumb">
          <td><%= link_to image_tag(oremeshi.finalimage.url, :size =>'480x320'), oremeshi %></td>
        </div>
      </th>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/oremeshis/new.html.erb
<h1>新兵追加</h1>

<%= render 'form', oremeshi: @oremeshi %>

<%= link_to 'Back', oremeshis_path %>

app/views/oremeshis/show.html.erb
<p id="notice"><%= notice %></p>

<div class="recipe">
<p>
  <h1><%= @oremeshi.title %></h1>
</p>

<p>
  <strong>具:</strong>
  <%= @oremeshi.ingre %>
</p>

<p>
  <strong>流-壱:</strong>
  <%= @oremeshi.step1 %>
</p>

<p>
  <%#= image_tag @oremeshi.finalimage.thumb.url %>
  <%= image_tag @oremeshi.image1.url, :size =>'480x320' %>
</p>

<p>
  <strong>　 弐:</strong>
  <%= @oremeshi.step2 %>
</p>

<p>
  <%#= image_tag @oremeshi.finalimage.thumb.url %>
  <%= image_tag @oremeshi.image2.url, :size =>'480x320' %>
</p>

<p>
  <strong>　 参:</strong>
  <%= @oremeshi.step3 %>
</p>

<p>
  <%#= image_tag @oremeshi.finalimage.thumb.url %>
  <%= image_tag @oremeshi.image3.url, :size =>'480x320' %>
</p>

<p>
  <strong>　 四:</strong>
  <%= @oremeshi.step4 %>
</p>

<p>
  <%#= image_tag @oremeshi.finalimage.thumb.url %>
  <%= image_tag @oremeshi.image4.url, :size =>'480x320' %>
</p>

<p>
  <strong>　 伍:</strong>
  <%= @oremeshi.final %>
  
</p>

<p>
  <%#= image_tag @oremeshi.finalimage.thumb.url %>
  <%= image_tag @oremeshi.finalimage.url, :size =>'480x320' %>
</p>

<p>
  <strong>刻:</strong>
  <%= @oremeshi.time %>
  <strong>分</strong>
</p>

<p>
  <strong>属:</strong>
  <%= @oremeshi.category %>
</p>
</div>

<%= link_to 'Edit', edit_oremeshi_path(@oremeshi) %> |
<%= link_to 'Back', oremeshis_path %>